name: erp_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # flutter_web_plugins:
  #   sdk: flutter

  dio: ^4.0.6
  http: ^0.13.5
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_modular: ^6.0.0-alpha.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:


  uses-material-design: true

